clear; clc;

% % READ DATA from Rockland diagnostic information file (DTA required)
% fileID=fopen('../DUA/assessment_data/DiagnosticInfo.csv','r');         % note name of file changed for purposes of data protection
% SUB_diagnosis=textscan(fileID,'%s %s %s %s %s %s %s %s %s %s %s %s','Delimiter',',');
% fclose(fileID);
% save NPEP.mat SUB SUB_diagnosis

% Reading different columns from the Psychometric data file
file = '/Users/mac637-jbj-100/Desktop/Neurofeedback/NKI-merged demographic and assessment data_5.28.19.xlsx';

raw_diagnosis_data = [readtable(file, 'Sheet', 'MEDICAL-Dx-LABS-Hx-Rx', 'Range', 'A:A'),...
                  readtable(file, 'Sheet', 'MEDICAL-Dx-LABS-Hx-Rx', 'Range', 'I:I')];

index = 1;              
for i = 1:height(raw_diagnosis_data)
    if contains(raw_diagnosis_data{i,1}, "A000") && ~strcmp(raw_diagnosis_data{i,2}, "")
        diagnosis_data(index,:) = raw_diagnosis_data{i,:};
        index = index + 1;
    else
        disp(i);
    end
end

save('diagnosis_data.mat', 'diagnosis_data');

%% Testing for reading multiple different columns from different Excel sheets from the same Excel file
% %DEMO-SCANinfo _2017... (2)    Columns: BZ, EV, ABG, ABT
% demo_scan = [readtable(file, 'Sheet', 'DEMO-SCANinfo _2017... (2)', 'Range', 'A:A'),...
%              readtable(file, 'Sheet', 'DEMO-SCANinfo _2017... (2)', 'Range', 'BZ:BZ'),...
%              readtable(file, 'Sheet', 'DEMO-SCANinfo _2017... (2)', 'Range', 'EV:EV'),...
%              readtable(file, 'Sheet', 'DEMO-SCANinfo _2017... (2)', 'Range', 'ABG:ABG'),...
%              readtable(file, 'Sheet', 'DEMO-SCANinfo _2017... (2)', 'Range', 'ABT:ABT')];
% 
% %PSYCHOMETRICS(1)_20170713     Columns: X:Y,AS,BL,BN,CQ,IH:II,JP:JR
% psych_1 = [readtable(file, 'Sheet', 'PSYCHOMETRICS(1)_20170713', 'Range', 'A:A'),...
%            readtable(file, 'Sheet', 'PSYCHOMETRICS(1)_20170713', 'Range', 'X:Y'),...
%            readtable(file, 'Sheet', 'PSYCHOMETRICS(1)_20170713', 'Range', 'AS:AS'),...
%            readtable(file, 'Sheet', 'PSYCHOMETRICS(1)_20170713', 'Range', 'BL:BL'),...
%            readtable(file, 'Sheet', 'PSYCHOMETRICS(1)_20170713', 'Range', 'BN:BN'),...
%            readtable(file, 'Sheet', 'PSYCHOMETRICS(1)_20170713', 'Range', 'CQ:CQ'),...
%            readtable(file, 'Sheet', 'PSYCHOMETRICS(1)_20170713', 'Range', 'IH:II'),...
%            readtable(file, 'Sheet', 'PSYCHOMETRICS(1)_20170713', 'Range', 'JO:JR')];

% %PSYCH2 Columns: AR:AV,EO:FF,HT:HY
% psych_2 = [readtable(file, 'Sheet', 'PSYCHOMETRICS(2)-20170713', 'Range', 'A:A'),...
%            readtable(file, 'Sheet', 'PSYCHOMETRICS(2)-20170713', 'Range', 'AR:AV'),...
%            readtable(file, 'Sheet', 'PSYCHOMETRICS(2)-20170713', 'Range', 'EO:FF'),...
%            readtable(file, 'Sheet', 'PSYCHOMETRICS(2)-20170713', 'Range', 'HT:HY')];

% %PSYCH3 Columns:
% %AY:BC,DL:DQ,DR,DS,DT:DX,NU:OH,OK:OM,OW:OY,TK:TN,TP:UA,ZC:ZF
% psych_3 = [readtable(file, 'Sheet', 'PSYCHOMETRICS(3)', 'Range', 'A:A'),...
%            readtable(file, 'Sheet', 'PSYCHOMETRICS(3)', 'Range', 'AY:BC'),...
%            readtable(file, 'Sheet', 'PSYCHOMETRICS(3)', 'Range', 'DL:DQ'),...
%            readtable(file, 'Sheet', 'PSYCHOMETRICS(3)', 'Range', 'DR:DR'),...
%            readtable(file, 'Sheet', 'PSYCHOMETRICS(3)', 'Range', 'DS:DS'),...
%            readtable(file, 'Sheet', 'PSYCHOMETRICS(3)', 'Range', 'DT:DX'),...
%            readtable(file, 'Sheet', 'PSYCHOMETRICS(3)', 'Range', 'NU:OH'),...
%            readtable(file, 'Sheet', 'PSYCHOMETRICS(3)', 'Range', 'OK:OM'),...
%            readtable(file, 'Sheet', 'PSYCHOMETRICS(3)', 'Range', 'OW:OY'),...
%            readtable(file, 'Sheet', 'PSYCHOMETRICS(3)', 'Range', 'TK:TN'),...
%            readtable(file, 'Sheet', 'PSYCHOMETRICS(3)', 'Range', 'TP:UA'),...
%            readtable(file, 'Sheet', 'PSYCHOMETRICS(3)', 'Range', 'ZC:ZF')];